site_name: obsidian-mkdocs template

theme:
    name: 'material'
    palette:
  # +------------------------------------------------------------------------------------------------------+
  # |                                                                                                      |
  # | The "palette" section is a Material option and allows you to define specific style options such as   |
  # | Color-Scheme, and primary and secondary Color.                                                       |
  # |                                                                                                      |
  # | You can also define multiple palettes that can have different Color Schemses and primary and/or      |
  # | secondary Colors.                                                                                    |
  # |                                                                                                      |
  # | Read More:                                                                                           |
  # | - https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/                             |
  # | - https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # +------------------------------------------------------------------------------------------------------+
  # |                                                                                                      |
  # | With the "font" option can you set a different font to use.                                          |
  # |                                                                                                      |
  # | Material supports all Google fonts, but you can also define your own ones if you choose so.          |
  # |                                                                                                      |
  # | The "text" option is used for the regular font while "code" is used for code blocks, inline code and |
  # | similar.                                                                                             |
  # |                                                                                                      |
  # | Read More:                                                                                           |
  # | - https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/                              |
  # |                                                                                                      |
  # +------------------------------------------------------------------------------------------------------+
    font:
      text: 'Lora'
      code: 'JetBrains Mono'


    # set edit option in page with jump to edit_uri:
    features:
      # code
      - content.code.copy
      - content.action.edit
      # - content.code.select  can be enable for insiders
      # footnotes
      - content.footnote.tooltips
      # prefect page
      - navigation.instant
      - navigation.instant.prefetch
      # top-level selection move to top tabs
      - navigation.tabs
      # top-2 section rendered
      - navigation.sections
      # back to top
      - navigation.top
    icon:
      edit: material/pencil
      view: material/eye
      # set icon to repo: https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit+uri#code-actions-edit-this-page:~:text=Some%20popular%20choices%3A
      repo: fontawesome/brands/github
      logo: logo-monochrome


# To display a link to the repository of your project as part of your documentation: https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit+uri#code-actions-edit-this-page:~:text=In%20order%20to%20display%20a%20link%20to%20the%20repository%20of%20your%20project%20as%20part%20of%20your%20documentation
repo_url: https://github.com/Atticuszz/mkdocs-obsidian-template
# set repo name
repo_name: Atticuszz/mkdocs-obsidian-template

edit_uri: edit/main/docs # Uncomment to define a different URI/URL for the "edit" option


# +--------------------------------------------------------------------------------------------------------+
# |                                                                                                        |
# | MkDocs allows the usage of Markdown extensions which can do various things.                            |
# |                                                                                                        |
# | Material includes the pymdownx extension which provides a lot of useful features to use.               |
# |                                                                                                        |
# | Note that some extensions may use specific settings that you need to set.                              |
# | Please check out the official documentation of PyMdownx for more information:                          |
# | https://facelessuser.github.io/pymdown-extensions/                                                     |
# |                                                                                                        |
# | Material already provides required CSS and JS values for the PyMdownX Extensions, which means you do   |
# | not need to set them up yourself.                                                                      |
# |                                                                                                        |
# | Read More:                                                                                             |
# | - https://www.mkdocs.org/user-guide/configuration/#markdown_extensions                                 |
# |                                                                                                        |
# +--------------------------------------------------------------------------------------------------------+
markdown_extensions:
  # admonition setting: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks-inline-end:~:text=Custom%20admonitions-,Admonitions,-%C2%B6
  - admonition
  - pymdownx.details




  # mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # attr_list
  - attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.toc:
      permalink: true

  # - pymdownx.b64
  # - pymdownx.betterem
  # - pymdownx.caret
  # - pymdownx.critic
  # - pymdownx.escapeall
  # - pymdownx.extra
  # - pymdownx.extrarawhtml

  # - pymdownx.keys
  # - pymdownx.magiclink

  # - pymdownx.pathconverter
  # - pymdownx.progressbar
  # - pymdownx.smartsymbols
  # -
  # - pymdownx.striphtml
  # - pymdownx.tabbed
  # list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
    # math
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.tilde
  #code
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # table
  - tables
  # footnotes
  - footnotes

  ## Formatting
  # highlight
  - pymdownx.mark
  # strikethrough
  - pymdownx.tilde
  # emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Image
  - md_in_html
plugins:
  # image zoom
  - glightbox
  - search
  - roamlinks
  - blog
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
# math and mermaid
extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js